# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitRepoPractical' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitRepoPractical
  pod 'ReachabilitySwift'

  target 'GitRepoPracticalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GitRepoPracticalUITests' do
    # Pods for testing
  end

end
